#!/bin/bash

# This script is aimed at making trying stuff out in the VM easier

tmux att -t from-kinesis-to-druid ||
tmux \
  new -s from-kinesis-to-druid -n druid \; \
  send-keys 'cd /app/; ./run-druid' C-m \; \
  neww -n stop-druid \; \
  send-keys './stop-druid' \; \
  neww -n tranquility \; \
  send-keys 'sleep 10; cd /app/to-druid/tranquility-distribution-0.8.0; bin/tranquility server -configFile ../tranquility-server-conf-from-druid-quickstart.json' C-m \; \
  neww -n testing \; \
  send-keys 'sleep 60; cd /app/to-druid/; ./generate-example-metrics | curl -XPOST -H"Content-Type: application/json" --data-binary @- http://localhost:8200/v1/post/eventer' C-m \; \
  neww -n kill-session \; \
  send-keys 'tmux kill-session -t from-kinesis-to-druid' \; \
  selectw -t testing
