#!/bin/bash

cd
mkdir -p foreign_src/
cd foreign_src
brew install wget
wget -O - http://static.druid.io/artifacts/releases/druid-0.9.2-bin.tar.gz | tar -xzf -
brew install zookeeper
cd /usr/local/etc/zookeeper
cp zoo_sample.cfg zoo.cfg

brew install Caskroom/cask/virtualbox
brew install Caskroom/cask/vagrant
