#!/usr/bin/env python

# Note: this script was copied from druid-0.9.2's bin folder and put here.  I
# didn't want to have to include the entire druid-0.9.2 simply to get this file
# and the tranquility-server-conf-from-druid-quickstart.json file that I also
# copied into this project.

import argparse
import json
import random
import sys
import datetime

def main():
  parser = argparse.ArgumentParser(description='Generate example page request latency metrics.')
  parser.add_argument('--count', '-c', type=int, default=25, help='Number of events to generate (negative for unlimited)')
  args = parser.parse_args()

  count = 0
  while args.count < 0 or count < args.count:
    random_seconds = float(random.randint(1,60*60*24*30))
    seconds_per_day = float(60*60*24)
    timestamp = (datetime.datetime.utcnow() - datetime.timedelta(random_seconds/seconds_per_day)).strftime("%Y-%m-%dT%H:%M:%SZ")

    r = random.randint(1, 4)
    if r == 1 or r == 2:
      page = '/'
    elif r == 3:
      page = '/list'
    else:
      page = '/get/' + str(random.randint(1, 99))

    server = 'www' + str(random.randint(1, 5)) + '.example.com'

    latency = max(1, random.gauss(80, 40))

    print(json.dumps({
      'timestamp': timestamp,
      'metricType': 'request/latency',
      'value': int(latency),

      # Additional dimensions
      'page': page,
      'server': server,
      'http_method': 'GET',
      'http_code': '200',
      'unit': 'milliseconds',

      # eventer dimensions
      'event_type': random.choice(['information', 'warning', 'error', 'critical'])
    }))

    count += 1

try:
  main()
except KeyboardInterrupt:
  sys.exit(1)
